### PR TITLE
Fix typo resource_by_name => resources_by_name

### PR DESCRIPTION
**Pull request by cjh1**

### CODE REVIEW

**Review by danlamanna — APPROVED** [review]

**Comment by brianhelba** [comment]
No, this should never have been merged here. PRs need to be made directly to https://github.com/girder/girder/tree/master/devops/ansible-role-girder

**Comment by brianhelba** [comment]
@cjh1 I'm going to have to revert this PR entirely to fix our deployment process. Can you please re-open the PR on https://github.com/girder/girder ?

**Comment by zachmullen** [comment]
@brianhelba I made you an admin over this repo, please change whatever settings you see fit to disable PRs or point people to the right repo.

**Comment by brianhelba** [comment]
@cjh1 I just applied your patch upstream: https://github.com/girder/girder/pull/3144

**Comment by brianhelba** [comment]
@zachmullen There's not much we can do technically to disable PRs or prevent admins from merging things in this repo. However, I think non-admins are now no longer able to merge to this repo.

**Comment by cjh1** [comment]
Thanks @brianhelba

**Pull request merged**
